export type CustomerReview = {
  customer: string;
  date: string;
  rating: number;
  product: string;
  comment: string;
  response?: string;
};

export const CUSTOMER_REVIEWS: CustomerReview[] = [
  {
    customer: "Leah",
    date: "16 Jul, 2026",
    rating: 5,
    product: "Black Kaftan Maxi Dress",
    comment: "I love it so much",
  },
  {
    customer: "Inès",
    date: "16 Jul, 2026",
    rating: 5,
    product: "Red Floral Cotton Napkin Set",
    comment: "Amazing product and fastly shipped, I recommend!",
    response: "Thank you so much for your wonderful review! 😊 We're delighted that you're happy with your purchase and the fast shipping. Your recommendation means a lot to us!",
  },
  {
    customer: "Inès",
    date: "16 Jul, 2026",
    rating: 5,
    product: "Red Floral Cotton Napkin Set",
    comment: "Perfect! Nisha was so nice with me as I needed the parcel for my wedding and it arrived in time",
    response: "Thank you so much for your kind words! 💕 It was a pleasure helping you, and we're so happy your parcel arrived in time for your wedding. Congratulations!",
  },
  {
    customer: "Leslie",
    date: "14 Jul, 2026",
    rating: 5,
    product: "Lavender Linen Ruffled Duvet Cover Set",
    comment: "Rich, saturated color. Solid, sturdy material. Well made. Arrived on time.",
    response: "Thank you for your wonderful feedback! We're delighted you loved the rich color, sturdy quality, and craftsmanship, and that it arrived on time.",
  },
  {
    customer: "Bugsy",
    date: "13 Jul, 2026",
    rating: 5,
    product: "Boho Block Print Kaftan Dress",
    comment: "Light, nice prints, fits well (as a caftan ought to). I'm an old hippie, love the look & comfort.",
    response: "Thank you for your wonderful feedback! We're so happy you love the lightweight fabric, beautiful prints, and comfortable fit. Enjoy your caftan!",
  },
  {
    customer: "Bugsy",
    date: "12 Jul, 2026",
    rating: 4,
    product: "Cotton Napkins",
    comment: "Ordered 14 x 14, napkins appear a little shorter (more like 13 x 14). Color is pretty. Shrinkage?",
    response: "Thank you for your feedback! Natural cotton can have a small amount of shrinkage after washing. We're glad you liked the color and appreciate your comments.",
  },
  {
    customer: "Simone",
    date: "12 Jul, 2026",
    rating: 4,
    product: "Boho Block Print Kaftan Dress",
    comment: "Adorable and very opaque. Just a bit sheer, so if you're going swimming be sure to also pack a towel as backup. Lovely styling piece.",
    response: "Thank you for your lovely feedback! We're so happy you found it adorable and loved the style. We appreciate your helpful comments!",
  },
  {
    customer: "Simone",
    date: "12 Jul, 2026",
    rating: 4,
    product: "Brown & Green Floral Cotton Sarong",
    comment: "The brown and green colorway is especially cute. They are rather sheer; wrap extra well for a beach cover. Real cotton/blend!",
    response: "Thank you for your thoughtful feedback! We're glad you loved the colors and appreciated the cotton fabric. Your helpful comments are appreciated.",
  },
  {
    customer: "Bugsy",
    date: "12 Jul, 2026",
    rating: 5,
    product: "Hand Block Print Cotton Bandana",
    comment: "Nice basic bandana, pleasing color.",
    response: "Thank you for your kind feedback! We're so happy you liked the color and the bandana.",
  },
  {
    customer: "Insight",
    date: "12 Jul, 2026",
    rating: 5,
    product: "Elegant Plum Linen Napkin Table Setting",
    comment: "The dress is as described and beautiful! The shipping was quick.",
    response: "Thank you so much for your wonderful feedback! We're delighted to hear you loved the item and that it arrived quickly.",
  },
  {
    customer: "Lucius",
    date: "11 Jul, 2026",
    rating: 5,
    product: "Set of 5 Cotton Bandanas",
    comment: "As advertised, but it actually looks a lot better in person than from the photos.",
    response: "Thank you so much! We're thrilled to hear the item exceeded your expectations and looked even better in person.",
  },
  {
    customer: "Catherine",
    date: "11 Jul, 2026",
    rating: 5,
    product: "Brown & Green Floral Cotton Sarong",
    comment: "Love this sarong, perfect colours, size and quality. Just what I was looking for. Delivery as expected, packaged well, can recommend!",
    response: "Thank you so much for your wonderful feedback! We're delighted you loved the colors, size, and quality. Your recommendation means a lot to us.",
  },
  {
    customer: "Helen",
    date: "11 Jul, 2026",
    rating: 4,
    product: "Handmade Pink Floral Cotton Quilted Duffle Bag",
    comment: "I love it but it's not as sturdy as I thought. However I do like it. The size is great, so thank you.",
    response: "Thank you for your thoughtful feedback! We're glad you love the size and appreciate your honest comments.",
  },
  {
    customer: "Etsy buyer",
    date: "09 Jul, 2026",
    rating: 4,
    product: "3 Piece Linen Bedding Set",
    comment: "This duvet cover was made of nice linen, and the sewing was well done. Unfortunately, the item was not the same colour as pictured.",
    response: "Thank you for your feedback. We're glad you liked the quality and craftsmanship, and we appreciate your honest review.",
  },
  {
    customer: "Stephanie",
    date: "09 Jul, 2026",
    rating: 5,
    product: "Linen Ruffle Tablecloth",
    comment: "My 2nd purchase. Very nice piece and will probably order more colors and sizes.",
    response: "Thank you so much for your wonderful review! We're so happy you love your purchase and are considering more colors and sizes.",
  },
  {
    customer: "Cynthia",
    date: "08 Jul, 2026",
    rating: 4,
    product: "Linen Ruffle Tablecloth",
    comment: "Beautiful print, but fabric is extremely lightweight.",
    response: "Thank you for your feedback! We're glad you liked the print and appreciate your comments about the fabric.",
  },
  {
    customer: "Macie",
    date: "09 Jul, 2026",
    rating: 1,
    product: "Boho Beach Sarong Wrap Skirt",
    comment: "The item appeared more elegant than it was. I did not like the material or the way it flowed on the body.",
  },
  {
    customer: "Selena",
    date: "08 Jul, 2026",
    rating: 1,
    product: "Elegant Mint Green Kaftan Maxi Dress",
    comment: "This is nothing like the dress in the photo; the cut and fabric are different. It's narrow, boxy, and has no style.",
  },
  {
    customer: "Emma",
    date: "07 Jul, 2026",
    rating: 5,
    product: "Boho Terracotta Kaftan Dress",
    comment: "Loved it!!! I can't wait to use it.",
    response: "Thank you so much for your lovely review! We're so happy to hear you love it. We hope you enjoy using it!",
  },
  {
    customer: "Kathy",
    date: "07 Jul, 2026",
    rating: 5,
    product: "Blush Pink Linen Ruffle Tablecloth",
    comment: "This is the second one I bought and I love them.",
    response: "Thank you so much for your wonderful review! We're delighted this is your second purchase and that you love them.",
  },
  {
    customer: "Brenna",
    date: "07 Jul, 2026",
    rating: 5,
    product: "Hand Block Print Cotton Vest",
    comment: "Amazing linen bedspread. The color and quality are amazing, and the customer service is super helpful! Highly recommend this vendor.",
    response: "Thank you so much for your 5-star review! We're thrilled you love the color, quality, and customer service. Thank you for your recommendation!",
  },
  {
    customer: "Micha",
    date: "07 Jul, 2026",
    rating: 1,
    product: "Pink Floral Block Print Bandana",
    comment: "Nothing like the picture, took a long time to be delivered too. Big disappointment, can't even wear it.",
  },
  {
    customer: "Vera",
    date: "06 Jul, 2026",
    rating: 2,
    product: "Elegant Solid Plum Kaftan Dress",
    comment: "The dress is different from the photo and the material does not have the expected quality. Delivery cost is expensive, but customer service is good.",
  },
  {
    customer: "Ella",
    date: "06 Jul, 2026",
    rating: 5,
    product: "3 Piece Linen Bedding Set",
    comment: "My comforter set was just as described!! Very comfy and well crafted, and the customer service was amazing!!",
    response: "Thank you so much for your wonderful 5-star review! We're delighted you found it comfortable, well-crafted, and exactly as described.",
  },
  {
    customer: "Josie",
    date: "04 Jul, 2026",
    rating: 5,
    product: "Plum Ruffled Linen Duvet Cover Set",
    comment: "Very comfortable, love the color.",
    response: "Thank you so much for your wonderful feedback! We're so happy you found it comfortable and loved the color.",
  },
  {
    customer: "Ingrid",
    date: "03 Jul, 2026",
    rating: 4,
    product: "Elegant Mint Green Kaftan Maxi Dress",
    comment: "I wanted to keep this but it's just too small. Nice garment, just make sure you get your measurements first.",
    response: "Thank you for your honest feedback! We're glad you liked the garment, and we appreciate you mentioning the sizing.",
  },
  {
    customer: "Martine",
    date: "04 Jul, 2026",
    rating: 4,
    product: "Hand Block Print Cotton Vest",
    comment: "The color is different from the photo.",
    response: "Thank you for your feedback. We're sorry the color wasn't exactly as expected and appreciate your support.",
  },
  {
    customer: "Diana",
    date: "03 Jul, 2026",
    rating: 5,
    product: "Dusty Rose Linen Duvet Cover Set",
    comment: "No complaints.",
    response: "Thank you so much for your wonderful feedback! We're delighted that everything met your expectations.",
  },
  {
    customer: "Customer",
    date: "14 Jul, 2026",
    rating: 5,
    product: "Handmade Cotton Caftan Collection",
    comment: "Lovely prints, comfort, and a wonderful 60s–70s vibe.",
    response: "Thank you so much for your lovely feedback! We're delighted you love the prints, comfort, and the 60s–70s vibe. Enjoy your caftans! 💕",
  },
];
